using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using MtgExplorer.Mtg;
using Neo4jClient;

namespace MtgExplorer.Generators
{
    public static class SetGenerator
    {
        public static ReadOnlyDictionary<string, NodeReference<SetNode>> SetNodes { get; private set; }
        private static bool _Initialized;
        public static void Create(GraphClient client)
        {
            if (_Initialized)
            {
                return;
            }

            var nodes = new Dictionary<string, NodeReference<SetNode>>(StringComparer.OrdinalIgnoreCase);
            foreach (var set in Sets)
            {
                
                var nodeRef = client.Create(set);
                nodes.Add(set.Name, nodeRef);
            }


            SetNodes = new ReadOnlyDictionary<string, NodeReference<SetNode>>(nodes);
            _Initialized = true;
        }

        public static readonly SetNode[] Sets = new[]
            {
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Alara Reborn", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Alliances", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Antiquities", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Apocalypse", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Arabian Nights", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Archenemy", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Avacyn Restored", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Battle Royale Box SetNode", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Beatdown Box SetNode", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Betrayers of Kamigawa", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Champions of Kamigawa", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Chronicles", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Classic Sixth Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Coldsnap", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Commander's Arsenal", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Conflux", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Dark Ascension", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Darksteel", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Dissension", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                //new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Dragon's Maze", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Ajani vs. Nicol Bolas", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Divine vs. Demonic", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Elspeth vs. Tezzeret", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Elves vs. Goblins", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Garruk vs. Liliana", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Izzet vs. Golgari", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Jace vs. Chandra", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Knights vs. Dragons", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Phyrexia vs. the Coalition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Duel Decks: Venser vs. Koth", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Eighth Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Eventide", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Exodus", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Fallen Empires", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Fifth Dawn", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Fifth Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Fourth Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "From the Vault: Dragons", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "From the Vault: Exiled", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "From the Vault: Legends", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "From the Vault: Realms", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "From the Vault: Relics", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Future Sight", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Gatecrash", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Guildpact", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Homelands", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Ice Age", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Innistrad", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Invasion", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Judgment", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Legends", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Legions", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Limited Edition Alpha", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Limited Edition Beta", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Lorwyn", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Magic 2010", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Magic 2011", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Magic 2012", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Magic 2013", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                //new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Magic 2014", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Magic: The Gathering-Commander", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Masters Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Masters Edition II", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Masters Edition III", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Masters Edition IV", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Mercadian Masques", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Mirage", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Mirrodin", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Mirrodin Besieged", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Morningtide", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Nemesis", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "New Phyrexia", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Ninth Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Odyssey", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Onslaught", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Planar Chaos", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Planechase", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Planechase 2012 Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Planeshift", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Portal", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Portal Second Age", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Portal Three Kingdoms", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Premium Deck Series: Fire and Lightning", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Premium Deck Series: Graveborn", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Premium Deck Series: Slivers", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Promo SetNode for Gatherer", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Prophecy", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Ravnica: City of Guilds", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Return to Ravnica", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Revised Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Rise of the Eldrazi", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Saviors of Kamigawa", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Scars of Mirrodin", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Scourge", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Seventh Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Shadowmoor", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Shards of Alara", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Starter 1999", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Starter 2000", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Stronghold", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Tempest", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Tenth Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "The Dark", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Time Spiral", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Time Spiral," + "Timeshifted", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Torment", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Unglued", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Unhinged", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Unlimited Edition", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Urza's Destiny", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Urza's Legacy", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Urza's Saga", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Vanguard", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Visions", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Weatherlight", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Worldwake", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1},
                new SetNode {ReleaseDate = new DateTime(2000, 02, 5), Name = "Zendikar", ExpansionCode = "", PreReleaseDate = new DateTime(2000, 02, 5),TotalCards = -1, Common = -1, Uncommon = -1, Rare = -1, BasicLand = -1}
            };

        public static readonly string[] SetNames = new[]
            {
                "Alara Reborn",
                "Alliances",
                "Antiquities",
                "Apocalypse",
                "Arabian Nights",
                "Archenemy",
                "Avacyn Restored",
                "Battle Royale Box Set",
                "Beatdown Box Set",
                "Betrayers of Kamigawa",
                "Champions of Kamigawa",
                "Chronicles",
                "Classic Sixth Edition",
                "Coldsnap",
                "Commander's Arsenal",
                "Conflux",
                "Dark Ascension",
                "Darksteel",
                "Dissension",
                //"Dragon's Maze",
                "Duel Decks: Ajani vs. Nicol Bolas",
                "Duel Decks: Divine vs. Demonic",
                "Duel Decks: Elspeth vs. Tezzeret",
                "Duel Decks: Elves vs. Goblins",
                "Duel Decks: Garruk vs. Liliana",
                "Duel Decks: Izzet vs. Golgari",
                "Duel Decks: Jace vs. Chandra",
                "Duel Decks: Knights vs. Dragons",
                "Duel Decks: Phyrexia vs. the Coalition",
                "Duel Decks: Venser vs. Koth",
                "Eighth Edition",
                "Eventide",
                "Exodus",
                "Fallen Empires",
                "Fifth Dawn",
                "Fifth Edition",
                "Fourth Edition",
                "From the Vault: Dragons",
                "From the Vault: Exiled",
                "From the Vault: Legends",
                "From the Vault: Realms",
                "From the Vault: Relics",
                "Future Sight",
                "Gatecrash",
                "Guildpact",
                "Homelands",
                "Ice Age",
                "Innistrad",
                "Invasion",
                "Judgment",
                "Legends",
                "Legions",
                "Limited Edition Alpha",
                "Limited Edition Beta",
                "Lorwyn",
                "Magic 2010",
                "Magic 2011",
                "Magic 2012",
                "Magic 2013",
                //"Magic 2014",
                "Magic: The Gathering-Commander",
                "Masters Edition",
                "Masters Edition II",
                "Masters Edition III",
                "Masters Edition IV",
                "Mercadian Masques",
                "Mirage",
                "Mirrodin",
                "Mirrodin Besieged",
                "Morningtide",
                "Nemesis",
                "New Phyrexia",
                "Ninth Edition",
                "Odyssey",
                "Onslaught",
                "Planar Chaos",
                "Planechase",
                "Planechase 2012 Edition",
                "Planeshift",
                "Portal",
                "Portal Second Age",
                "Portal Three Kingdoms",
                "Premium Deck Series: Fire and Lightning",
                "Premium Deck Series: Graveborn",
                "Premium Deck Series: Slivers",
                "Promo set for Gatherer",
                "Prophecy",
                "Ravnica: City of Guilds",
                "Return to Ravnica",
                "Revised Edition",
                "Rise of the Eldrazi",
                "Saviors of Kamigawa",
                "Scars of Mirrodin",
                "Scourge",
                "Seventh Edition",
                "Shadowmoor",
                "Shards of Alara",
                "Starter 1999",
                "Starter 2000",
                "Stronghold",
                "Tempest",
                "Tenth Edition",
                "The Dark",
                "Time Spiral",
                "Time Spiral," +
                "Timeshifted",
                "Torment",
                "Unglued",
                "Unhinged",
                "Unlimited Edition",
                "Urza's Destiny",
                "Urza's Legacy",
                "Urza's Saga",
                "Vanguard",
                "Visions",
                "Weatherlight",
                "Worldwake",
                "Zendikar"
            };
    }
}